version: "3.7"
services:
  site:
    build:
      context: .
      target: flaskapp
    restart: unless-stopped
    ports:
      - "7331:7331"
    volumes:
      - ${PWD}/settings.json:/app/settings.json
      - ${PWD}/logs/:/app/logs/
    environment:
      - TZ=Europe/Stockholm
  bot:
    build:
      context: .
      target: discordbot
    restart: unless-stopped
    volumes:
      - ${PWD}/settings.json:/app/settings.json
      - ${PWD}/users.json:/app/users.json
      - ${PWD}/logs/:/app/logs/
    environment:
      - TZ=Europe/Stockholm
